import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { dbStore } from "@/db";
import { hasPermission } from "@/lib/permissions";

export const runtime = "edge";

export async function GET() {
  const session = await getSession();
  if (!session || !session.mandalId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!hasPermission(session.role, session.permissions, "finance.view")) {
    return NextResponse.json({ error: "Permission denied" }, { status: 403 });
  }

  const donationsList = dbStore.getDonations(session.mandalId);
  return NextResponse.json({ donations: donationsList });
}

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session || !session.mandalId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!hasPermission(session.role, session.permissions, "finance.create")) {
    return NextResponse.json({ error: "Permission denied" }, { status: 403 });
  }

  try {
    const body = await req.json();
    const {
      donor_name,
      donor_name_mr,
      contact_number,
      address,
      amount_pledged,
      amount_paid,
      payment_mode,
      payment_date,
      notes,
    } = body;

    if (!donor_name || amount_pledged === undefined) {
      return NextResponse.json(
        { error: "Donor name and pledged amount are required" },
        { status: 400 }
      );
    }

    const pledged = Number(amount_pledged) || 0;
    const paid = Number(amount_paid) || 0;
    const pending = Math.max(0, pledged - paid);

    const newDonation = dbStore.createDonation({
      id: `don-${Date.now()}`,
      mandal_id: session.mandalId,
      receipt_no: "", // Auto-generated by store
      donor_name,
      donor_name_mr: donor_name_mr || null,
      contact_number: contact_number || null,
      address: address || null,
      amount_pledged: pledged,
      amount_paid: paid,
      balance_pending: pending,
      payment_mode: payment_mode || "cash",
      payment_date: payment_date || new Date().toISOString().split("T")[0],
      notes: notes || null,
      received_by_name: session.name,
    });

    return NextResponse.json({ success: true, donation: newDonation });
  } catch (err: unknown) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to record donation" },
      { status: 500 }
    );
  }
}
